-- ============================================================================
-- DATABASE MANAGEMENT SYSTEM: EV CHARGING STATION NETWORK
-- SCRIPT 03: DATABASE TEARDOWN / CLEANUP SCRIPT (Reverse FK Dependency Order)
-- ============================================================================

DROP TABLE IF EXISTS COMPLAINTS;
DROP TABLE IF EXISTS REVIEWS;
DROP TABLE IF EXISTS PAYMENTS;
DROP TABLE IF EXISTS CHARGING_SESSIONS;
DROP TABLE IF EXISTS BOOKINGS;
DROP TABLE IF EXISTS VEHICLES;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS PRICES;
DROP TABLE IF EXISTS PORTS;
DROP TABLE IF EXISTS STATIONS;
DROP TABLE IF EXISTS OPERATORS;
